2018/02/19 07:31:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'நீங்கள் வேண்டிய "contactd" செயல் இந்த தளத்தில் இல்லை.' in D:\xampp\htdocs\wishYii\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(270): CController->missingAction('contactd')
#1 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(282): CController->run('contactd')
#2 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contactd')
#3 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#5 {main}
REQUEST_URI=/wishyii/index.php?r=site/contactd
---
2018/02/19 07:40:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=gii
---
2018/02/19 07:44:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "wish ".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/
---
2018/02/19 07:44:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "wish ".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/
---
2018/02/19 07:44:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "wish ".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/
---
2018/02/19 07:53:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "contact".' in D:\xampp\htdocs\wishYii\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(270): CController->missingAction('contact')
#1 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('wish/contact')
#3 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#5 {main}
REQUEST_URI=/wishyii/index.php?r=wish/contact
HTTP_REFERER=http://localhost/wishyii/index.php?r=site/contact
---
2018/02/19 07:54:47 [error] [php] mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (D:\xampp\htdocs\wishYii\protected\controllers\WishController.php:67)
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(286): WishController->runAction()
#2 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(265): WishController->runActionWithFilters()
#3 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(282): WishController->run()
#4 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 D:\xampp\htdocs\wishYii\index.php(16): CWebApplication->run()
REQUEST_URI=/wishyii/index.php?r=wish/contact
in D:\xampp\htdocs\wishYii\protected\controllers\WishController.php (67)
in D:\xampp\htdocs\wishYii\index.php (16)
2018/02/19 07:56:21 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "index".' in D:\xampp\htdocs\wishYii\yii\framework\web\CController.php:878
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 D:\xampp\htdocs\wishYii\protected\controllers\SiteController.php(32): CController->render('index')
#2 D:\xampp\htdocs\wishYii\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\xampp\htdocs\wishYii\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(282): CController->run('index')
#7 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#8 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#10 {main}
REQUEST_URI=/wishyii/index.php?r=site/index
---
2018/02/19 07:57:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site2/contact".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site2/contact')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=site2/contact
---
2018/02/19 07:57:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "site2/contact".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site2/contact')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=site2/contact
---
2018/02/19 08:04:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:05:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:05:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:05:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:07:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:07:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:07:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:07:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
2018/02/19 08:07:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "dfh".' in D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\wishYii\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('dfh')
#1 D:\xampp\htdocs\wishYii\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 D:\xampp\htdocs\wishYii\index.php(16): CApplication->run()
#3 {main}
REQUEST_URI=/wishyii/index.php?r=dfh
---
